#!/usr/bin/env python3
"""Build the Navigator read model for document registration candidates.

The YAML candidate ledger remains the human-review source. This script compiles it
into deterministic JSON for the static browser client. The preview is explicitly
non-canonical and must never modify docs_manifest.yml or search ranking.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = Path("tools/docs_registration_candidates.yml")
DEFAULT_OUTPUT = Path("tools/docs_registration_candidates.preview.json")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_candidate_source(path: Path) -> tuple[dict, bytes]:
    raw = path.read_bytes()
    data = yaml.safe_load(raw.decode("utf-8", errors="strict"))
    if not isinstance(data, dict) or not isinstance(data.get("registration_candidates"), dict):
        raise ValueError("registration_candidates root object is required")
    return data, raw


def validate_alignment(root: Path, payload: dict) -> list[str]:
    errors: list[str] = []
    source = payload.get("source", {})
    manifest_rel = str(source.get("manifest_path") or "tools/docs_manifest.yml")
    graph_rel = str(source.get("graph_path") or "tools/docs_graph.json")
    manifest_path = root / manifest_rel
    graph_path = root / graph_rel
    if not manifest_path.is_file():
        errors.append(f"missing manifest source: {manifest_rel}")
    else:
        actual = sha256_bytes(manifest_path.read_bytes())
        expected = str(source.get("manifest_sha256") or "")
        if expected and actual != expected:
            errors.append(f"manifest hash mismatch: candidate={expected} current={actual}")
    if not graph_path.is_file():
        errors.append(f"missing graph source: {graph_rel}")
    else:
        actual = sha256_bytes(graph_path.read_bytes())
        expected = str(source.get("graph_sha256") or "")
        if expected and actual != expected:
            errors.append(f"graph hash mismatch: candidate={expected} current={actual}")
    policy = payload.get("policy", {})
    promoted = bool(policy.get("promoted_as_provisional_registration"))
    if not promoted:
        if policy.get("candidate_only") is not True:
            errors.append("candidate_only policy must be true before promotion")
        if policy.get("manifest_is_not_modified") is not True:
            errors.append("manifest_is_not_modified policy must be true before promotion")
    candidates = payload.get("candidates", [])
    if not isinstance(candidates, list):
        errors.append("candidates must be an array")
    else:
        expected_count = payload.get("summary", {}).get("total_candidates")
        if expected_count is not None and int(expected_count) != len(candidates):
            errors.append(f"summary total_candidates mismatch: summary={expected_count} actual={len(candidates)}")
    return errors


def build_document(source_data: dict, source_raw: bytes) -> dict:
    # Preserve the reviewed YAML structure verbatim as JSON-compatible data.
    # Add only a source hash so the browser can expose whether the read model is stale.
    root = json.loads(json.dumps(source_data, ensure_ascii=False))
    payload = root["registration_candidates"]
    payload.setdefault("source", {})["candidate_source_sha256"] = sha256_bytes(source_raw)
    payload["source"]["preview_contract"] = "review/audit source; provisional entries are now canonical manifest records; not search ranking"
    return root


def serialize(data: dict) -> bytes:
    return (json.dumps(data, ensure_ascii=False, indent=2, sort_keys=False) + "\n").encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build deterministic registration-candidate JSON for Navigator preview.")
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--source", default=str(DEFAULT_SOURCE))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true", help="Compare generated bytes with tracked preview JSON without writing.")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    source_path = root / args.source
    output_path = root / args.output

    try:
        source_data, source_raw = load_candidate_source(source_path)
        payload = source_data["registration_candidates"]
        alignment_errors = validate_alignment(root, payload)
        if alignment_errors:
            print("REGISTRATION CANDIDATE PREVIEW BUILD BLOCKED", file=sys.stderr)
            for error in alignment_errors:
                print(f"ERROR {error}", file=sys.stderr)
            return 1
        generated = serialize(build_document(source_data, source_raw))
    except (OSError, UnicodeDecodeError, ValueError, yaml.YAMLError, json.JSONDecodeError) as exc:
        print(f"REGISTRATION CANDIDATE PREVIEW BUILD FAILED: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not output_path.is_file():
            print(f"REGISTRATION CANDIDATE PREVIEW CHECK FAILED: missing {output_path.relative_to(root)}", file=sys.stderr)
            return 1
        current = output_path.read_bytes()
        if current != generated:
            print("REGISTRATION CANDIDATE PREVIEW CHECK FAILED: generated preview is stale", file=sys.stderr)
            return 1
        print(f"REGISTRATION CANDIDATE PREVIEW CHECK PASS: {len(payload.get('candidates', []))} candidates")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(generated.decode("utf-8"))
    print(f"REGISTRATION CANDIDATE PREVIEW BUILT: {output_path.relative_to(root)} ({len(payload.get('candidates', []))} candidates)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
